
extern zend_class_entry *oauth2_clientassertiontype_clientassertiontypeinterface_ce;

ZEPHIR_INIT_CLASS(OAuth2_ClientAssertionType_ClientAssertionTypeInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_oauth2_clientassertiontype_clientassertiontypeinterface_validaterequest, 0, 0, 2)
	ZEND_ARG_OBJ_INFO(0, request, OAuth2\\RequestInterface, 0)
	ZEND_ARG_OBJ_INFO(0, response, OAuth2\\ResponseInterface, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(oauth2_clientassertiontype_clientassertiontypeinterface_method_entry) {
	PHP_ABSTRACT_ME(OAuth2_ClientAssertionType_ClientAssertionTypeInterface, validateRequest, arginfo_oauth2_clientassertiontype_clientassertiontypeinterface_validaterequest)
	PHP_ABSTRACT_ME(OAuth2_ClientAssertionType_ClientAssertionTypeInterface, getClientId, NULL)
  PHP_FE_END
};
