#!/bin/bash
export CC="gcc"
export CFLAGS="-O2 -Wall -fvisibility=hidden -flto -DZEPHIR_RELEASE=1"
if [ -f Makefile ]; then
	make --silent clean
	phpize --silent --clean
fi
phpize --silent
./configure --silent --enable-oauth2
make --silent && make --silent install
