
/* This file was generated automatically by Zephir do not modify it! */

#ifndef ZEPHIR_CLASS_ENTRIES_H
#define ZEPHIR_CLASS_ENTRIES_H

#include "oauth2/autoloader.zep.h"
#include "oauth2/clientassertiontype/clientassertiontypeinterface.zep.h"
#include "oauth2/clientassertiontype/httpbasic.zep.h"
#include "oauth2/controller/authorizecontrollerinterface.zep.h"
#include "oauth2/controller/resourcecontroller.zep.h"
#include "oauth2/controller/resourcecontrollerinterface.zep.h"
#include "oauth2/controller/tokencontroller.zep.h"
#include "oauth2/controller/tokencontrollerinterface.zep.h"
#include "oauth2/encryption/encryptioninterface.zep.h"
#include "oauth2/exception.zep.h"
#include "oauth2/granttype/authorizationcode.zep.h"
#include "oauth2/granttype/clientcredentials.zep.h"
#include "oauth2/granttype/granttypeinterface.zep.h"
#include "oauth2/granttype/jwtbearer.zep.h"
#include "oauth2/granttype/refreshtoken.zep.h"
#include "oauth2/granttype/usercredentials.zep.h"
#include "oauth2/requestinterface.zep.h"
#include "oauth2/responseinterface.zep.h"
#include "oauth2/responsetype/accesstoken.zep.h"
#include "oauth2/responsetype/accesstokeninterface.zep.h"
#include "oauth2/responsetype/authorizationcode.zep.h"
#include "oauth2/responsetype/authorizationcodeinterface.zep.h"
#include "oauth2/responsetype/responsetypeinterface.zep.h"
#include "oauth2/scope.zep.h"
#include "oauth2/scopeinterface.zep.h"
#include "oauth2/storage/accesstokeninterface.zep.h"
#include "oauth2/storage/authorizationcodeinterface.zep.h"
#include "oauth2/storage/clientcredentialsinterface.zep.h"
#include "oauth2/storage/clientinterface.zep.h"
#include "oauth2/storage/jwtaccesstoken.zep.h"
#include "oauth2/storage/jwtaccesstokeninterface.zep.h"
#include "oauth2/storage/jwtbearerinterface.zep.h"
#include "oauth2/storage/publickeyinterface.zep.h"
#include "oauth2/storage/refreshtokeninterface.zep.h"
#include "oauth2/storage/scopeinterface.zep.h"
#include "oauth2/storage/storageinterface.zep.h"
#include "oauth2/storage/usercredentialsinterface.zep.h"
#include "oauth2/tokentype/bearer.zep.h"
#include "oauth2/tokentype/mac.zep.h"
#include "oauth2/tokentype/tokentypeinterface.zep.h"

#endif